[package]
name = "rustbucket"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
figment = { version = "0.10.19", features = ["toml"] }
reqwest = { version = "0.11", features = ["json"] }
config = "0.14.0"