# Rustbucket Configuration
[general]
# The log level for the application
log_level = "info"

# Directory for storing logs
log_directory = "./logs"

# Whether to enable verbose logging
verbose = false

# Enable or disable specific ports
[ports]
ssh = { enabled = true, port = 22 }
http = { enabled = true, port = 80 }
ftp = { enabled = false, port = 21 }
# Add more services as needed
