# Rustbucket Configuration
[general]
# The log level for the application
log_level = "info"

# Directory for storing logs
log_directory = "./logs"

# Whether to enable verbose logging
verbose = false

[ports]
ssh = { enabled = true, port = 22 }
http = { enabled = true, port = 80 }
ftp = { enabled = false, port = 21 }
sftp = { enabled = false, port = 115 }
smtp = { enabled = false, port = 25 }
dns = { enabled = false, port = 53 }
sms = { enabled = false, port = 5000 }

[openai]
api_key = "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"

[openai.static_messages]
message1 = "Hi ChatGPT! You are the backend for a honeypot. An unknown user has connected to the honeypot and is executing actions on it. The user is not aware that they are interacting with a honeypot. The goal is to gather information about the user's intentions and actions. I need you to act like an Ubuntu server and respond to the user's commands like a server would."
message2 = "Please maintain the history of each command and always respond as if you were an actual Ubuntu server. Don't respond using full sentences, or the user will know it's you! If the user inputs an invalid command or text, please respond with 'Invalid Command'."
message3 = "The user has closed the session. Please save the history of the session and prepare for the next user."
